### ISSUE TITLE
型定義ファイルのexportをdefaultにしたい

### ISSUE THREAD

**Issue by becyn** [openfresh/super-image#21]
もし問題がなければ、以下のexport部分を `export default SuperImage;` として
`import { default as SuperImage} from 'super-image';` といった感じでimportしたいです。
https://github.com/openfresh/super-image/blob/master/type/index.d.ts#L22

いかがでしょうか👀？

既存のままで `import SuperImage from 'super-image';` でimportすると
TS1192（Module has no default export. ）のwarningが出てしまいます。

**Comment by tommy-san** [comment]
@becyn 👇 じゃダメなんでしたっけ？
```ts
import * as SuperImage from 'super-image';
```
